version: '3.7'
services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_LISTENERS: INSIDE://kafka:29092,OUTSIDE://kafka:9092,LOCALHOST://kafka:9093
#     Use the localhost advertised listener when accessing from outside the docker network (testing)      
#      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://kafka:9092,LOCALHOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,LOCALHOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "streams-plaintext-input:1:1, streams-pipe-output:1:1"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock

  # employee-administration:
  #   build: ./employee-administration/.
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - zookeeper
  #     - kafka  

  # project-administration:
  #   build: ./projectadministration/.
  #   ports:
  #     - "8090:8090"
  #   depends_on:
  #     - zookeeper
  #     - kafka

  # worktime-administration:
  #   build: ./worktime-administration/.
  #   ports:
  #     - "8085:8085"
  #   depends_on:
  #     - zookeeper
  #     - kafka          
      