spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true
      path: /console

  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8090
