spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true
      path: /console

#  kafka:
#    consumer:
#      bootstrap-servers: ${spring.kafka.}
#    bootstrap-servers: ${spring.embedded.kafka.brokers}

  jackson:
    serialization:
      write-dates-as-timestamps: false