spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true
      path: /console

#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: employee
#      auto-offset-reset: earliest
#      enable-auto-commit: false
#    bootstrap-servers: localhost:9092

  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080