spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true
      path: /console
      settings:
        web-allow-others: true

  #  kafka:
#    consumer:
#      bootstrap-servers: ${KAFKA_URL}
#      group-id: employee
#      auto-offset-reset: earliest
#      enable-auto-commit: false
#    bootstrap-servers: ${KAFKA_URL}

  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080