spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true
      path: /console


  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: employee
    bootstrap-servers: localhost:9092

  jackson:
    serialization:
      write-dates-as-timestamps: false